from models.Empresa import Empresa
from models.Lenguaje import Lenguaje
from models.Programador import Programador

def init_db():
    print("creando empresas...")

    google = Empresa(nombre='Google', fundacion=1998)
    microsoft = Empresa(nombre='Microsoft', fundacion=1975)
    apple = Empresa(nombre='Apple', fundacion=1975)
    amazon = Empresa(nombre='Amazon', fundacion=1999)
    ebay = Empresa(nombre='Ebay', fundacion=1997)
    facebook = Empresa(nombre='Facebook', fundacion=2004)
    twitter = Empresa(nombre='Twitter', fundacion=2009)
    yahoo = Empresa(nombre='Yahoo', fundacion=1996)
    snapchat = Empresa(nombre='Snapchat', fundacion=2012)
    instagram = Empresa(nombre='Instagram', fundacion=2010)

    google.save()
    microsoft.save()
    apple.save()
    amazon.save()
    ebay.save()
    facebook.save()
    twitter.save()
    yahoo.save()
    snapchat.save()
    instagram.save()

    print("creando lenguajes...")
    java = Lenguaje(nombre='java', creador='James Gosling')
    c = Lenguaje(nombre='c', creador='Dennis Ritchie')
    python = Lenguaje(nombre='python', creador='Guido Van Rossum')
    haskell = Lenguaje(nombre='haskell')
    javascript = Lenguaje(nombre='javascript', creador='Brendan Eich')
    basic = Lenguaje(nombre='basic', creador='John G. Kemeny')
    cplusplus = Lenguaje(nombre='c++', creador='Bjarne Stroustrup')
    csharp = Lenguaje(nombre='c#')
    swift = Lenguaje(nombre='swift', creador='Chris Lattner')
    kotlin = Lenguaje(nombre='kotlin')

    java.save()
    c.save()
    python.save()
    haskell.save()
    javascript.save()
    basic.save()
    cplusplus.save()
    csharp.save()
    swift.save()
    kotlin.save()

    john = Programador(nombre='Jonh', edad=22)
    juan = Programador(nombre='Juan', edad=22)
    jose = Programador(nombre='Jose', edad=25)
    edgar = Programador(nombre='Edgar', edad=26)
    mark = Programador(nombre='Mark', edad=26)
    venus = Programador(nombre='Venus', edad=28)
    sol = Programador(nombre='Sol', edad=28)
    andrea = Programador(nombre='Andrea', edad=29)
    cardi = Programador(nombre='Cardi', edad=23)
    maria = Programador(nombre='Maria', edad=23)
    joel = Programador(nombre='Joel', edad=24)
    salman = Programador(nombre='Salman', edad=25)
    tabata = Programador(nombre='Tabata', edad=27)

    # john = Programador(nombre='Jonh', edad=22, empresa=apple)
    # juan = Programador(nombre='Juan', edad=22, empresa=apple)
    # jose = Programador(nombre='Jose', edad=25, empresa=twitter)
    # edgar = Programador(nombre='Edgar', edad=26, empresa=twitter)
    # mark = Programador(nombre='Mark', edad=26, empresa=facebook)
    # venus = Programador(nombre='Venus', edad=28, empresa=snapchat)
    # sol = Programador(nombre='Sol', edad=28, empresa=snapchat)
    # andrea = Programador(nombre='Andrea', edad=29, empresa=yahoo)
    # cardi = Programador(nombre='Cardi', edad=23, empresa=amazon)
    # maria = Programador(nombre='Maria', edad=23, empresa=google)
    # joel = Programador(nombre='Joel', edad=24, empresa=google)
    # salman = Programador(nombre='Salman', edad=25, empresa=google)
    # tabata = Programador(nombre='Tabata', edad=27, empresa=ebay)
    
    andrea.empresa = snapchat

    # andrea.lenguajes.append(javascript)
    # andrea.lenguajes.append(python)
    # andrea.lenguajes.append(kotlin)
    # joel.lenguajes.append(kotlin)
    # venus.lenguajes.append(kotlin)

    john.save()
    juan.save()
    jose.save()
    edgar.save()
    mark.save()
    venus.save()
    sol.save()
    andrea.save()
    cardi.save()
    maria.save()
    joel.save()
    salman.save()
    tabata.save()

    print("todo ha sido creado...")